server:
  port: 8084

spring:
  application:
    name: hgt-pay
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hgt3306
    url: jdbc:mysql://localhost:3306/willlink_market_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      max-lifetime: 120
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  type-aliases-package: com.hgt.*.entity
  mapper-locations: classpath:mapper/*.xml

